### ISSUE TITLE
Can we add the file base64?

### ISSUE THREAD

**Issue by lindexi** [Towmeykaw/dotnet-base64#2]
Can we make the file to base64 and save to other file?

**Comment by Towmeykaw** [comment]
In powershell its possible to pipe the output of the command to the Out-file cmdlet. So something like `base64 stringToEncode | Out-File -FilePath .\test.txt` should work

**Comment by lindexi** [comment]
@Towmeykaw How about this command? 

base64 -f TheInputFile -o TheOutputFile

Why I want to add file base64? because I want to use this code that should convert the file as base64 to save to github secrets

https://github.com/microsoft/github-actions-for-desktop-apps/blob/59a4b373c3ee1afb0f9e2481ac262913638a4923/.github/workflows/ci.yml#L78

**Comment by Towmeykaw** [comment]
Sounds interesting. I just pushed a version 1.2.0. Have a look and see if it solves your problem.

**Comment by lindexi** [comment]
@Towmeykaw Thank you
